spring:
  application:
    name: FioonYang-center
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.railway.internal:3306/railway?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: qLHipXRjUMplpYRafMLAmAuQjeOQVHib
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  session:
    timeout: 86400

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fy.usercenter.model.domain
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 8080

knife4j:
  enable: true
  setting:
    enable-version: true
    enable-swagger-models: true
