server:
  port: ${PORT:8080}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&connectTimeout=60000&socketTimeout=60000&createDatabaseIfNotExist=true
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
      minimum-idle: 5
  sql:
    init:
      mode: always
      schema-locations: classpath:init.sql
      continue-on-error: true
  
  # 生产环境配置
  profiles:
    active: prod

# MyBatis-Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

# 日志配置
logging:
  level:
    com.fy.usercenter: INFO
    org.springframework: WARN
    root: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"