[phases.setup]
nixPkgs = ['jdk21', 'maven']

[phases.build]
cmds = ['mvn clean package -DskipTests']

[phases.start]
cmd = 'java -Xmx512m -Xms256m -jar target/user-center-backend-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod'

[variables]
JAVA_OPTS = '-Xmx512m -Xms256m'
