[phases.setup]
nixPkgs = ['jdk8', 'maven']

[phases.build]
cmds = ['mvn clean package -DskipTests']

[phases.start]
cmd = 'java -Xmx512m -Xms256m -jar target/user-center-backend-0.0.1-SNAPSHOT.jar'

[variables]
JAVA_HOME = '/nix/store/*-openjdk-8*/'
JAVA_OPTS = '-Xmx512m -Xms256m'
